gui:
  authorColors:
    '*': '#0000ff'
    "Alper Doğan": "green"
  branchColors:
    'main': 'red'
  splitDiff: 'always'

os:
  editPreset: 'nvim'

git:
  mainBranches: ['main']
  paging:
    colorArg: always
    pager: delta --dark --color-only --side-by-side
