gui:
  authorColors:
    '*': '#0000ff'
    "Alper Doğan": "green"
  branchColors:
    'main': 'red'
    'master': 'red'
  # splitDiff: 'always'
  showCommandLog: true
  mainPanelSplitMode: 'horizontal'
  sidePanelWidth: 0.25

os:
  editPreset: 'nvim'

git:
  mainBranches: ['main']
  paging:
    colorArg: always
    pager: delta --dark --paging=never --side-by-side
    # pager: delta --color-only --dark --paging=never --side-by-side
