#!/usr/bin/env sh

# bsp, stack or float
yabai -m config layout bsp

yabai -m config window_placement second_child

# padding
yabai -m config top_padding 6
yabai -m config bottom_padding 6
yabai -m config left_padding 6
yabai -m config right_padding 6
yabai -m config window_gap 6

yabai -m config window_topmost on
yabai -m config window_opacity_duration 0.0

# yabai -m config window_opacity on
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.6
yabai -m config split_ratio                  0.50

# mouse settings
# yabai -m config mouse_follows_focus on

yabai -m config mouse_modifier fn
# left click + drag
yabai -m config mouse_action1 move

# right click + drag
yabai -m config mouse_action2 resize

yabai -m mouse_drop_action swap

# Disable yabai for these apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^Finder$" manage=off

echo "yabai configuration loaded.."

inactive_color=0xff696d66
active_color=0xffe1e3e6
# https://github.com/FelixKratz/JankyBorders
borders active_color=0x99ff0000 width=4 &
