return {
	"catppuccin/nvim",
	name = "catppuccin",
	priority = 1000,
	config = function()
		local catppuccin = require("catppuccin")
		catppuccin.setup({
			flavour = "mocha",
			background = {
				dark = "mocha",
				light = "latte",
			},
			no_italic = true,
			transparent_background = false,
			color_overrides = {
				frappe = {
					rosewater = "#BF616A",
					flamingo = "#BF616A",
					pink = "#B48EAD",
					mauve = "#B48EAD",
					red = "#BF616A",
					maroon = "#BF616A",
					peach = "#D08770",
					yellow = "#EBCB8B",
					green = "#A3BE8C",
					teal = "#88c0d0",
					sky = "#88c0d0",
					sapphire = "#88c0d0",
					blue = "#81a1c1",
					lavender = "#81a1c1",
					text = "#ECEFF4",
					subtext1 = "#E5E9F0",
					subtext0 = "#D8DEE9",
					overlay2 = "#8d9196",
					overlay1 = "#81858b",
					overlay0 = "#4C566A",
					surface2 = "#434C5E",
					surface1 = "#3B4252",
					surface0 = "#292e39",
					base = "#242933",
					mantle = "#20242d",
					crust = "#1c2028",
				},
				mocha = {
					rosewater = "#EA6962",
					flamingo = "#EA6962",
					pink = "#D3869B",
					mauve = "#D3869B",
					red = "#EA6962",
					maroon = "#EA6962",
					peach = "#BD6F3E",
					yellow = "#D8A657",
					green = "#A9B665",
					teal = "#89B482",
					sky = "#89B482",
					sapphire = "#89B482",
					blue = "#7DAEA3",
					lavender = "#7DAEA3",
					text = "#D4BE98",
					subtext1 = "#BDAE8B",
					subtext0 = "#A69372",
					overlay2 = "#8C7A58",
					overlay1 = "#735F3F",
					overlay0 = "#5A4525",
					surface2 = "#4B4F51",
					surface1 = "#2A2D2E",
					surface0 = "#232728",
					base = "#1D2021",
					mantle = "#191C1D",
					crust = "#151819",
					prompt = "#FFFFFF",
				},
				latte = {
					rosewater = "#984d54",
					flamingo = "#984d54",
					pink = "#90718a",
					mauve = "#90718a",
					red = "#984d54",
					maroon = "#984d54",
					peach = "#a66c59",
					yellow = "#bca26f",
					green = "#829870",
					teal = "#6c99a6",
					sky = "#6c99a6",
					sapphire = "#6c99a6",
					blue = "#67809a",
					lavender = "#67809a",
					text = "#2E3440",
					subtext1 = "#3B4252",
					subtext0 = "#434C5E",
					overlay2 = "#4C566A",
					overlay1 = "#818896",
					overlay0 = "#9399a5",
					surface2 = "#a5aab4",
					surface1 = "#b7bbc3",
					surface0 = "#c9ccd2",
					base = "#ECEFF4",
					mantle = "#E5E9F0",
					crust = "#D8DEE9",
				},
			},
			styles = {
				comments = { "italic" },
				conditionals = { "italic" },
				loops = { "bold" },
				functions = { "bold" },
				keywords = { "bold" },
				strings = {},
				variables = {},
				numbers = { "bold" },
				booleans = { "bold" },
				properties = {},
				types = { "bold" },
				operators = {},
			},
			custom_highlights = function(colors)
				return {
					LineNr = { fg = colors.red },
					NormalFloat = { bg = colors.crust },
					FloatBorder = { fg = colors.crust },
					VertSplit = { bg = colors.base, fg = colors.surface0 },
					CursorLineNr = { fg = colors.red, style = { "bold" } },
					TelescopeSelection = { bg = colors.surface0 },
					TelescopePromptCounter = { fg = colors.mauve, style = { "bold" } },
					TelescopePromptPrefix = { bg = colors.surface0 },
					TelescopePromptNormal = { bg = colors.surface0 },
					TelescopeResultsNormal = { bg = colors.mantle },
					TelescopePreviewNormal = { bg = colors.crust },
					TelescopePromptBorder = { bg = colors.surface0, fg = colors.surface0 },
					TelescopeResultsBorder = { bg = colors.mantle, fg = colors.mantle },
					TelescopePreviewBorder = { bg = colors.crust, fg = colors.crust },
					TelescopePromptTitle = { fg = colors.prompt, bg = colors.surface0 },
					TelescopeResultsTitle = { fg = colors.mantle, bg = colors.mantle },
					TelescopePreviewTitle = { fg = colors.crust, bg = colors.crust },
					Pmenu = { bg = colors.crust, fg = "" },
					PmenuSel = { bg = colors.surface0, fg = "" },
					IndentBlanklineChar = { fg = colors.surface0 },
					IndentBlanklineContextChar = { fg = colors.surface2 },
					GitSignsChange = { fg = colors.peach },
					NvimTreeIndentMarker = { link = "IndentBlanklineChar" },
					NvimTreeExecFile = { fg = colors.text },
				}
			end,
		})

		vim.cmd("colorscheme catppuccin")
	end,
}
